# Generated by Django 3.2.8 on 2021-11-01 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashaworkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password2', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('adharno', models.CharField(max_length=100)),
                ('idcard', models.ImageField(null=True, upload_to='images/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('qualification', models.ImageField(null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
