# Generated by Django 3.2.8 on 2021-11-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Asha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=500)),
                ('feedback', models.CharField(max_length=1000)),
                ('ashaworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.ashaworkerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=500)),
                ('feedback', models.CharField(max_length=1000)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.patiententry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.usertype')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
