# Generated by Django 3.2.8 on 2021-11-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0006_askdoctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askdoctor',
            name='doctor',
        ),
    ]
