# Generated by Django 3.2.8 on 2021-11-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0007_remove_askdoctor_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='askdoctor',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.doctorentry'),
        ),
    ]
