# Generated by Django 3.2.8 on 2021-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0008_askdoctor_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiententry',
            name='age',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='checkstart',
            field=models.DateField(default='2021-10-11'),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='confirmdate',
            field=models.DateField(default='2021-10-11'),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='issue',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='job',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='medicines',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='qualification',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='patiententry',
            name='wedding',
            field=models.DateField(default='2021-10-11'),
        ),
    ]
