# Generated by Django 3.2.8 on 2021-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0009_auto_20211105_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='patiententry',
            name='address',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
