# Generated by Django 3.2.8 on 2021-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0010_patiententry_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashaworkerentry',
            name='ward',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='patiententry',
            name='age',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
