# Generated by Django 3.2.8 on 2021-11-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0011_auto_20211106_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahusname', models.CharField(max_length=100)),
                ('fahusno', models.CharField(max_length=1000)),
                ('noofchild', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('address', models.CharField(default='0', max_length=1000)),
                ('wedding', models.DateField(default='2021-10-11')),
                ('qualification', models.CharField(default='0', max_length=100)),
                ('age', models.CharField(default='0', max_length=100, null=True)),
                ('job', models.CharField(default='0', max_length=100)),
                ('medicines', models.CharField(default='0', max_length=1000)),
                ('checkstart', models.DateField(default='2021-10-11')),
                ('confirmdate', models.DateField(default='2021-10-11')),
                ('issue', models.CharField(default='0', max_length=1000)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.patiententry')),
            ],
        ),
    ]
