# Generated by Django 3.2.8 on 2021-11-09 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashaworkapp', '0012_patient_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(default='2021-10-11')),
                ('hospitalname', models.CharField(max_length=400)),
                ('place', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=200)),
                ('firstvaccinedate', models.DateField(default='2021-10-11')),
                ('birthcertificate', models.ImageField(null=True, upload_to='images/')),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.patiententry')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preg_Women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(default='2021-10-11')),
                ('firstcheckup', models.DateField(default='2021-10-11')),
                ('hospitalname', models.CharField(max_length=500)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.patiententry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ashaworkerentry',
            name='city',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='ashaworkerentry',
            name='husname',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='ashaworkerentry',
            name='panchayath',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='ashaworkerentry',
            name='street',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.DeleteModel(
            name='Patient_Module',
        ),
    ]
