# Generated by Django 3.2.8 on 2021-11-09 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ashaworkapp', '0014_alter_child_module_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newly_Married',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpanchayath', models.CharField(max_length=300)),
                ('oldstreet', models.CharField(max_length=300)),
                ('oldwardno', models.CharField(max_length=200)),
                ('medicines', models.CharField(max_length=500)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashaworkapp.patiententry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
