# Generated by Django 3.2.8 on 2021-11-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashaworkapp', '0015_newly_married'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child_module',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newly_married',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preg_women',
            name='user',
        ),
    ]
